apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/att-user-produce
  newTag: 7590c473


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: att-user-produce-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: att-user-produce-secret-env
