apiVersion: apps/v1
kind: Deployment
metadata:
  name: att-user-produce
  labels:
    app.kubernetes.io/name: att-user-produce
    app.kubernetes.io/instance: att-user-produce
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: att-user-produce
      app.kubernetes.io/instance: att-user-produce
  template:
    metadata:
      labels:
        app.kubernetes.io/name: att-user-produce
        app.kubernetes.io/instance: att-user-produce
    spec:
      containers:
        - name: att-user-produce
          image: asia.gcr.io/poc-innovation-iot/att-user-produce:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: att-user-produce-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: att-user-produce-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: att-user-produce-secret-file
          secret:
            secretName: att-user-produce-secret-file
        - name: att-user-produce-configmap-file
          configMap:
            name: att-user-produce-configmap-file

        