apiVersion: v1
kind: Service
metadata:
  name: att-user-produce
  labels:
    app.kubernetes.io/name: att-user-produce
    app.kubernetes.io/instance: att-user-produce
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: att-user-produce
    app.kubernetes.io/instance: att-user-produce
